//
//  MyFullTimeJobViewController.swift
//  RecruitManner
//
//  Created by Jiang Duan on 16/11/25.
//  Copyright (c) 2016年 Jiang Duan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import MJRefresh

protocol MyFullTimeJobViewControllerInput
{
    func displaySomething(viewModel: MyFullTimeJob.ViewModel)
}

protocol MyFullTimeJobViewControllerOutput
{
    func doSomething(request: MyFullTimeJob.Request)
}


// ============================================================================= //
// MARK: - MyFullTimeJobViewController Class Definition
// ============================================================================= //
class MyFullTimeJobViewController: UITableViewController, MyFullTimeJobViewControllerInput
{
    var output: MyFullTimeJobViewControllerOutput!
    var router: MyFullTimeJobRouter!
    
    // MARK: Object lifecycle
    
    override func awakeFromNib()
    {
        super.awakeFromNib()
        MyFullTimeJobConfigurator.sharedInstance.configure(viewController:self)
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        
        self.tableView.mj_header = MJRefreshNormalHeader(refreshingBlock: { [weak self] in
            self?.tableView.mj_header.endRefreshing()
        })
        self.tableView.tableFooterView = UIView()
        
        doSomethingOnLoad()
    }
    
    // MARK: Event handling
    
    func doSomethingOnLoad()
    {
        // NOTE: Ask the Interactor to do some work
        
        let request = MyFullTimeJob.Request()
        output.doSomething(request: request)
    }
    
    // MARK: Display logic
    
    func displaySomething(viewModel: MyFullTimeJob.ViewModel)
    {
        // NOTE: Display the result from the Presenter
        
        // nameTextField.text = viewModel.name
    }
}

extension MyFullTimeJobViewController {
    
    override func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return 5
    }
    
    override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let Identifier = "CellMyFullTimeJobIdentifier"
        let cell = tableView.dequeueReusableCell(withIdentifier: Identifier, for: indexPath)
        
        return cell
    }
    
}
