//
//  SingleCompanyTrackViewController.swift
//  RecruitManner
//
//  Created by Jiang Duan on 16/11/23.
//  Copyright (c) 2016年 Jiang Duan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import DLSlideView

protocol SingleCompanyTrackViewControllerInput {

    func displaySomething(viewModel: SingleCompanyTrack.ViewModel)
}

protocol SingleCompanyTrackViewControllerOutput {

    func doSomething(request: SingleCompanyTrack.Request)
}


// ============================================================================= //
// MARK: - SingleCompanyTrackViewController Class Definition
// ============================================================================= //
class SingleCompanyTrackViewController: UIViewController, SingleCompanyTrackViewControllerInput {

    var output: SingleCompanyTrackViewControllerOutput!
    var router: SingleCompanyTrackRouter!
    
    @IBOutlet weak var tabedSlideView: DLTabedSlideView!
  
    // MARK: Object lifecycle
  
    override func awakeFromNib() {

        super.awakeFromNib()
        SingleCompanyTrackConfigurator.sharedInstance.configure(viewController:self)
    }
  
    // MARK: View lifecycle
  
    override func viewDidLoad() {

        super.viewDidLoad()
        doSomethingOnLoad()
    }
  
    // MARK: Event handling
  
    func doSomethingOnLoad() {
        // NOTE: Ask the Interactor to do some work
    
        let request = SingleCompanyTrack.Request()
        output.doSomething(request: request)
    }
  
    // MARK: Display logic
  
    func displaySomething(viewModel: SingleCompanyTrack.ViewModel) {
        // NOTE: Display the result from the Presenter
    
        // nameTextField.text = viewModel.name
        tabedSlideView.baseViewController = self
        tabedSlideView.tabItemNormalColor = UIColor.black
        tabedSlideView.tabItemSelectedColor = UIColor(red: 0.833, green: 0.052, blue: 0.130, alpha: 1.0)
        tabedSlideView.tabbarTrackColor = UIColor(red: 0.833, green: 0.052, blue: 0.130, alpha: 1.0)
        tabedSlideView.tabbarBackgroundImage = UIImage(named: "tabbarBk")
        tabedSlideView.tabbarBottomSpacing = 3.0
        
        let item1 = DLTabedbarItem(title: "Web前端", image: UIImage(named: "goodsNew"), selectedImage: UIImage(named: "goodsNew_d"))
        let item2 = DLTabedbarItem(title: "HR经理", image: UIImage(named: "goodsHot"), selectedImage: UIImage(named: "goodsHot_d"))
        let item3 = DLTabedbarItem(title: "销售", image: UIImage(named: "goodsPrice"), selectedImage: UIImage(named: "goodsPrice_d"))
        tabedSlideView.tabbarItems = [item1!, item2!, item3!]
        tabedSlideView.buildTabbar()
        
        tabedSlideView.selectedIndex = 0
    }
}


extension SingleCompanyTrackViewController: DLTabedSlideViewDelegate {
    
    func numberOfTabs(in sender: DLTabedSlideView!) -> Int {
        return tabedSlideView.tabbarItems.count
    }
    
    func dlTabedSlideView(_ sender: DLTabedSlideView!, controllerAt index: Int) -> UIViewController! {
        
        let ctrl = ResumeDeliverTableViewController.storyboardInstance()
        return ctrl
        
    }

}
