//
//  ConcernJobSeekerViewController.swift
//  RecruitManner
//
//  Created by Jiang Duan on 16/11/23.
//  Copyright (c) 2016年 Jiang Duan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ConcernJobSeekerViewControllerInput
{
    func displaySomething(viewModel: ConcernJobSeeker.ViewModel)
}

protocol ConcernJobSeekerViewControllerOutput
{
    func doSomething(request: ConcernJobSeeker.Request)
}


// ============================================================================= //
// MARK: - ConcernJobSeekerViewController Class Definition
// ============================================================================= //
class ConcernJobSeekerViewController: UITableViewController, ConcernJobSeekerViewControllerInput
{
    var output: ConcernJobSeekerViewControllerOutput!
    var router: ConcernJobSeekerRouter!
    
    // MARK: Object lifecycle
    
    override func awakeFromNib()
    {
        super.awakeFromNib()
        ConcernJobSeekerConfigurator.sharedInstance.configure(viewController:self)
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        doSomethingOnLoad()
    }
    
    // MARK: Event handling
    
    func doSomethingOnLoad()
    {
        // NOTE: Ask the Interactor to do some work
        
        let request = ConcernJobSeeker.Request()
        output.doSomething(request: request)
    }
    
    // MARK: Display logic
    
    func displaySomething(viewModel: ConcernJobSeeker.ViewModel)
    {
        // NOTE: Display the result from the Presenter
        
        // nameTextField.text = viewModel.name
    }
}

extension ConcernJobSeekerViewController {
    
    override func tableView(_ tableView: UITableView, titleForHeaderInSection section: Int) -> String? {
        return "深圳市阿里巴巴商务有限公司"
    }
    
    override func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return 5
    }
    
    override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let Identifier = "CellResumeDeliverIdentifier"
        let cell = tableView.dequeueReusableCell(withIdentifier: Identifier, for: indexPath)
        
        return cell
    }
    
}
