//
//  PayAttentionCompanysViewController.swift
//  RecruitManner
//
//  Created by Jiang Duan on 16/11/21.
//  Copyright (c) 2016年 Jiang Duan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol PayAttentionCompanysViewControllerInput
{
    func displaySomething(viewModel: PayAttentionCompanys.ViewModel)
}

protocol PayAttentionCompanysViewControllerOutput
{
    func doSomething(request: PayAttentionCompanys.Request)
}


// ============================================================================= //
// MARK: - PayAttentionCompanysViewController Class Definition
// ============================================================================= //
class PayAttentionCompanysViewController: UITableViewController, PayAttentionCompanysViewControllerInput
{
    var output: PayAttentionCompanysViewControllerOutput!
    var router: PayAttentionCompanysRouter!
    
    // MARK: Object lifecycle
    
    override func awakeFromNib()
    {
        super.awakeFromNib()
        PayAttentionCompanysConfigurator.sharedInstance.configure(viewController:self)
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        doSomethingOnLoad()
    }
    
    // MARK: Event handling
    
    func doSomethingOnLoad()
    {
        // NOTE: Ask the Interactor to do some work
        
        let request = PayAttentionCompanys.Request()
        output.doSomething(request: request)
    }
    
    // MARK: Display logic
    
    func displaySomething(viewModel: PayAttentionCompanys.ViewModel)
    {
        // NOTE: Display the result from the Presenter
        
        // nameTextField.text = viewModel.name
    }
}


extension PayAttentionCompanysViewController {
    
    override func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return 5
    }
    
    override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let Identifier = "PayAttentionCompanysIdentifier"
        let cell = tableView.dequeueReusableCell(withIdentifier: Identifier, for: indexPath)
        
        return cell
    }
}
