use_frameworks!

platform :ios, '8.0'

target :RecruitManner do

	# 公共库(必须)
	pod 'MOBFoundation', '~> 2.2.3'
	# 主模块(必须)
	pod 'ShareSDK2', '~> 2.12.5'
	# UI模块(含所有UI样式,可选)
	pod 'ShareSDK2/UI', '~> 2.12.5'
	# 新浪微博(可选)
	pod 'ShareSDK2/Connection/SinaWeibo', '~> 2.12.5'
	# 微信(可选)
	pod 'ShareSDK2/Connection/WeChat', '~> 2.12.5'
	# 腾讯QQ(可选)
	pod 'ShareSDK2/Connection/QQ', '~> 2.12.5'
	# QQ空间(可选)
	pod 'ShareSDK2/Connection/QZone', '~> 2.12.5'
	# 腾讯微博(可选)
	pod 'ShareSDK2/Connection/TencentWeibo', '~> 2.12.5'
    
    # HTTP + json
    pod 'Alamofire', :path => '../github/Alamofire'
    pod 'ObjectMapper', '~> 2.2.1'
    pod 'HandyJSON', '~> 1.2.1'
    
    # iOS图片、文字轮播器
    pod 'SDCycleScrollView'
    
    # 下拉刷新
    pod 'MJRefresh'
    
    # 单选框
    pod 'RadioButton'
    
    # 避免键盘遮挡下方输入框
    pod 'TPKeyboardAvoiding'
    
    # 可滑动Label
    #pod 'MarqueeLabel/Swift'
    
    # 下拉菜单
    # pod 'YZPullDownMenu'
    # pod 'DOPDropDownMenu-Enhanced', '~> 1.0.0'
    
    # 顶部Tab
    pod 'DLSlideView', :git => 'https://github.com/agdsdl/DLSlideView.git'
    
end

target :AlamofireObjectMapper do
    pod 'Alamofire', :path => '../github/Alamofire'
    pod 'ObjectMapper', '~> 2.2.1'
    pod 'HandyJSON', '~> 1.2.1'
end
