use_frameworks!

platform :ios, '8.0'

target :RecruitManner do

# 主模块(必须)
    pod 'ShareSDK3'
    pod 'ShareSDK3/ShareSDKExtension'
# Mob 公共库(必须) 如果同时集成SMSSDK iOS2.0:可看此注意事项：http://bbs.mob.com/thread-20051-1-1.html
    pod 'MOBFoundation'

# UI模块(非必须，需要用到ShareSDK提供的分享菜单栏和分享编辑页面需要以下1行)
    pod 'ShareSDK3/ShareSDKUI'

# 平台SDK模块(对照一下平台，需要的加上。如果只需要QQ、微信、新浪微博，只需要以下3行)
    pod 'ShareSDK3/ShareSDKPlatforms/QQ'
    pod 'ShareSDK3/ShareSDKPlatforms/SinaWeibo'
    pod 'ShareSDK3/ShareSDKPlatforms/WeChat'

    # HTTP + json
    pod 'Alamofire', :path => '../github/Alamofire'
    # pod 'ObjectMapper', '~> 2.2.1'
    pod 'HandyJSON', '~> 1.2.1'
    
    # iOS图片、文字轮播器
    pod 'SDCycleScrollView'
    
    # 下拉刷新
    pod 'MJRefresh'
    
    # 单选框
    pod 'RadioButton'
    
    # 避免键盘遮挡下方输入框
    pod 'TPKeyboardAvoiding'
    
    # 可滑动Label
    #pod 'MarqueeLabel/Swift'
    
    # 下拉菜单
    # pod 'YZPullDownMenu'
    # pod 'DOPDropDownMenu-Enhanced', '~> 1.0.0'
    
    # 顶部Tab
    pod 'DLSlideView', :git => 'https://github.com/agdsdl/DLSlideView.git'
    
end

target :AlamofireObjectMapper do
    pod 'Alamofire', :path => '../github/Alamofire'
    # pod 'ObjectMapper', '~> 2.2.1'
    pod 'HandyJSON', '~> 1.2.1'
end


target :RecruitMannerTests do
    
end
