use_frameworks!

platform :ios, '8.0'

target :RecruitManner do

	# 公共库(必须)
	pod 'MOBFoundation', '~> 2.2.3'
	# 主模块(必须)
	pod 'ShareSDK2', '~> 2.12.5'
	# UI模块(含所有UI样式,可选)
	pod 'ShareSDK2/UI', '~> 2.12.5'
	# 新浪微博(可选)
	pod 'ShareSDK2/Connection/SinaWeibo', '~> 2.12.5'
	# 微信(可选)
	pod 'ShareSDK2/Connection/WeChat', '~> 2.12.5'
	# 腾讯QQ(可选)
	pod 'ShareSDK2/Connection/QQ', '~> 2.12.5'
	# QQ空间(可选)
	pod 'ShareSDK2/Connection/QZone', '~> 2.12.5'
	# 腾讯微博(可选)
	pod 'ShareSDK2/Connection/TencentWeibo', '~> 2.12.5'
    
    
    pod 'Alamofire', :path => '../github/Alamofire'
    pod 'ObjectMapper', '~> 2.2.1'
    
end

target :AlamofireObjectMapper do
    pod 'Alamofire', :path => '../github/Alamofire'
    pod 'ObjectMapper', '~> 2.2.1'
end
