//
//  JobCityViewController.swift
//  RecruitManner
//
//  Created by xiaohui on 16/11/24.
//  Copyright (c) 2016年 Jiang Duan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol JobCityViewControllerInput {

    func displaySomething(viewModel: JobCity.ViewModel)
}

protocol JobCityViewControllerOutput {

    func doSomething(request: JobCity.Request)
}


// ============================================================================= //
// MARK: - JobCityViewController Class Definition
// ============================================================================= //
class JobCityViewController: UIViewController, JobCityViewControllerInput {

    var output: JobCityViewControllerOutput!
    var router: JobCityRouter!
  
    @IBOutlet weak var cityButtonView: UIView!
    // MARK: Object lifecycle
  
    override func awakeFromNib() {

        super.awakeFromNib()
        JobCityConfigurator.sharedInstance.configure(viewController:self)
    }
  
    // MARK: View lifecycle
  
    override func viewDidLoad() {

        super.viewDidLoad()
        doSomethingOnLoad()
        
    }
  
    // MARK: Event handling
  
    func doSomethingOnLoad() {
        // NOTE: Ask the Interactor to do some work
    
        let request = JobCity.Request()
        output.doSomething(request: request)
    }
  
    // MARK: Display logic
  
    func displaySomething(viewModel: JobCity.ViewModel) {
        // NOTE: Display the result from the Presenter
    
        // nameTextField.text = viewModel.name
    }
}
