//
//  CompanyHomePageInfosViewController.swift
//  RecruitManner
//
//  Created by Jiang Duan on 16/11/28.
//  Copyright (c) 2016年 Jiang Duan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import CustomViews

protocol CompanyHomePageInfosViewControllerInput
{
    func displaySomething(viewModel: CompanyHomePageInfos.ViewModel)
}

protocol CompanyHomePageInfosViewControllerOutput
{
    func doSomething(request: CompanyHomePageInfos.Request)
}


// ============================================================================= //
// MARK: - CompanyHomePageInfosViewController Class Definition
// ============================================================================= //
class CompanyHomePageInfosViewController: UITableViewController, CompanyHomePageInfosViewControllerInput
{
    var output: CompanyHomePageInfosViewControllerOutput!
    var router: CompanyHomePageInfosRouter!
    
    // MARK: Object lifecycle
    
    override func awakeFromNib()
    {
        super.awakeFromNib()
        CompanyHomePageInfosConfigurator.sharedInstance.configure(viewController:self)
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        doSomethingOnLoad()
    }
    
    // MARK: Event handling
    
    func doSomethingOnLoad()
    {
        // NOTE: Ask the Interactor to do some work
        
        let request = CompanyHomePageInfos.Request()
        output.doSomething(request: request)
    }
    
    // MARK: Display logic
    
    func displaySomething(viewModel: CompanyHomePageInfos.ViewModel)
    {
        // NOTE: Display the result from the Presenter
        
        // nameTextField.text = viewModel.name
    }
}

extension CompanyHomePageInfosViewController {
    
    
    override func numberOfSections(in tableView: UITableView) -> Int {
        return 2
    }
    
    override func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return 3
    }
    
    override func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        switch indexPath.section {
        case 0:
            return 120
        default:
            return 188
        }
    }
    
    override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        switch indexPath.section {
        case 0:
            return cellHomePost(forTableView: tableView, cellForRowAt: indexPath)
        default:
            return cellHomeResume(forTableView: tableView, cellForRowAt: indexPath)
        }
    }
    
    private func cellHomePost(forTableView tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let Identifier = "CellCompanyHomePagePostIdentifier"
        let cell = tableView.dequeueReusableCell(withIdentifier: Identifier, for: indexPath)
        
        let view = cell.viewWithTag(1) as? JobInfoItemView
        if indexPath.row != 0 {
            view?.isHiddenDate = true
        }
        
        return cell
    }
    
    private func cellHomeResume(forTableView tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let Identifier = "CellCompanyHomePageResumeIdentifier"
        let cell = tableView.dequeueReusableCell(withIdentifier: Identifier, for: indexPath)
        
        return cell
    }
}
