//
//  NewResumesViewController.swift
//  RecruitManner
//
//  Created by Jiang Duan on 16/11/23.
//  Copyright (c) 2016年 Jiang Duan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import CustomViews
import MJRefresh
import SDWebImage

protocol NewResumesViewControllerInput
{
    func displaySomething(viewModel: NewResumes.ViewModel)
}

protocol NewResumesViewControllerOutput
{
    func doSomething(request: NewResumes.Request)
}


// ============================================================================= //
// MARK: - NewResumesViewController Class Definition
// ============================================================================= //
class NewResumesViewController: UITableViewController, NewResumesViewControllerInput
{
    var output: NewResumesViewControllerOutput!
    var router: NewResumesRouter!
    
    var viewModel = NewResumes.ViewModel()
    
    // MARK: Object lifecycle
    
    override func awakeFromNib()
    {
        super.awakeFromNib()
        NewResumesConfigurator.sharedInstance.configure(viewController:self)
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        
        self.tableView.mj_header = MJRefreshNormalHeader() { [weak self] in
            self?.tableView.mj_header.endRefreshing()
        }
        
        doSomethingOnLoad()
    }
    
    // MARK: Event handling
    
    func doSomethingOnLoad()
    {
        // NOTE: Ask the Interactor to do some work
        
        let request = NewResumes.Request()
        output.doSomething(request: request)
    }
    
    // MARK: Display logic
    
    func displaySomething(viewModel: NewResumes.ViewModel)
    {
        // NOTE: Display the result from the Presenter
        
        self.viewModel = viewModel
        self.tableView.reloadData()
    }
}

extension NewResumesViewController {

    override func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return self.viewModel.resumes?.count ?? 0
    }

    override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let Identifier = "CellNewResumesIdentifier"
        let cell = tableView.dequeueReusableCell(withIdentifier: Identifier, for: indexPath)
        
        guard let model = self.viewModel.resumes?[indexPath.row] else {
            return cell
        }
        
        guard let view = cell.viewWithTag(1) as? ResumeItemView else {
            return cell
        }
        
        view.date = model.date
        view.nameText = model.name
        view.markText = model.mark
        let postString = model.positionTitle ?? ""
        view.postText = "投递给\"\(postString)\"的简历"
        
        if let urlstring = model.imageUrl, let url = URL(string: urlstring) {
            view.logoView.sd_setImageWithPreviousCachedImage(with: url,
                                                             placeholderImage: UIImage(named: "social_logo"),
                                                             options: .continueInBackground,
                                                             progress: nil,
                                                             completed: nil)
        }
    
        return cell
    }

}
