//
//  JobSeekerOfNearbyViewController.swift
//  RecruitManner
//
//  Created by Jiang Duan on 16/11/25.
//  Copyright (c) 2016年 Jiang Duan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import CustomViews

protocol JobSeekerOfNearbyViewControllerInput
{
    func displaySomething(viewModel: JobSeekerOfNearby.ViewModel)
}

protocol JobSeekerOfNearbyViewControllerOutput
{
    func doSomething(request: JobSeekerOfNearby.Request)
}


// ============================================================================= //
// MARK: - JobSeekerOfNearbyViewController Class Definition
// ============================================================================= //
class JobSeekerOfNearbyViewController: UITableViewController, JobSeekerOfNearbyViewControllerInput
{
    var output: JobSeekerOfNearbyViewControllerOutput!
    var router: JobSeekerOfNearbyRouter!
    
    @IBOutlet weak var headerView: UIView!
    
    // MARK: Object lifecycle
    
    override func awakeFromNib()
    {
        super.awakeFromNib()
        JobSeekerOfNearbyConfigurator.sharedInstance.configure(viewController:self)
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        
        if let menu = DOPDropDownMenu(origin: CGPoint(x:0,y:0), andHeight: 28) {
            menu.delegate = self
            menu.dataSource = self
            menu.backgroundColor = UIColor.green
            view.addSubview(menu)
            menu.selectDefalutIndexPath()
        }
        
        doSomethingOnLoad()
    }
    
    // MARK: Event handling
    
    func doSomethingOnLoad()
    {
        // NOTE: Ask the Interactor to do some work
        
        let request = JobSeekerOfNearby.Request()
        output.doSomething(request: request)
    }
    
    // MARK: Display logic
    
    func displaySomething(viewModel: JobSeekerOfNearby.ViewModel)
    {
        // NOTE: Display the result from the Presenter
        
        // nameTextField.text = viewModel.name
    }
}

extension JobSeekerOfNearbyViewController {
    
    override func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return 5
    }
    
    override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "cellJobSeekerOfNearbyIdentifier", for: indexPath)
        return cell
    }
}

extension JobSeekerOfNearbyViewController: DOPDropDownMenuDataSource, DOPDropDownMenuDelegate {

    func numberOfColumns(in menu: DOPDropDownMenu!) -> Int {
        return 3
    }
    
    func menu(_ menu: DOPDropDownMenu!, titleForRowAt indexPath: DOPIndexPath!) -> String! {
        return [["不限", "2k以下", "2k-5k", "5k-10k", "10k-15k", "15k-25k", "25k-50k", "50k以上"],
         ["不限", "大专及以上", "本科及以上", "硕士及以上", "博士及以上"],
         ["不限", "3年以下", "3年及以上", "7年及以上"]][indexPath.column][indexPath.row]
    }
    
    func menu(_ menu: DOPDropDownMenu!, numberOfRowsInColumn column: Int) -> Int {
        return [8, 5, 4][column]
    }
    
    func menu(_ menu: DOPDropDownMenu!, numberOfItemsInRow row: Int, column: Int) -> Int {
        return 0
    }
}
