//
//  OccupationalHistoryListViewController.swift
//  RecruitManner
//
//  Created by Jiang Duan on 16/11/14.
//  Copyright (c) 2016年 Jiang Duan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol OccupationalHistoryListViewControllerInput
{
    func displaySomething(viewModel: OccupationalHistoryList.ViewModel)
}

protocol OccupationalHistoryListViewControllerOutput
{
    func doSomething(request: OccupationalHistoryList.Request)
}


// ============================================================================= //
// MARK: - OccupationalHistoryListViewController Class Definition
// ============================================================================= //
class OccupationalHistoryListViewController: UITableViewController, OccupationalHistoryListViewControllerInput
{
    var output: OccupationalHistoryListViewControllerOutput!
    var router: OccupationalHistoryListRouter!
    
    // MARK: Object lifecycle
    
    override func awakeFromNib()
    {
        super.awakeFromNib()
        OccupationalHistoryListConfigurator.sharedInstance.configure(viewController:self)
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        doSomethingOnLoad()
    }
    
    // MARK: Event handling
    
    func doSomethingOnLoad()
    {
        // NOTE: Ask the Interactor to do some work
        
        let request = OccupationalHistoryList.Request()
        output.doSomething(request: request)
    }
    
    // MARK: Display logic
    
    func displaySomething(viewModel: OccupationalHistoryList.ViewModel)
    {
        // NOTE: Display the result from the Presenter
        
        // nameTextField.text = viewModel.name
    }
}


extension OccupationalHistoryListViewController {

    override func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return 5
    }
    
    override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let Identifier = "CellOccupationalHistoryIdentifier"
        let cell = tableView.dequeueReusableCell(withIdentifier: Identifier, for: indexPath)
        
        return cell
    }
    
}
